"""initial whatsapp schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 14:58:32.331603
"""

from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_accounts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('phone_number_id', sa.String(length=64), nullable=False),
    sa.Column('business_account_id', sa.String(length=64), nullable=True),
    sa.Column('display_phone_number', sa.String(length=32), nullable=True),
    sa.Column('verified_name', sa.String(length=255), nullable=True),
    sa.Column('agent_model', sa.String(length=255), nullable=False),
    sa.Column('auto_reply', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number_id')
    )
    op.create_table('whatsapp_contacts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('wa_id', sa.String(length=32), nullable=False),
    sa.Column('profile_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'wa_id', name='uq_contact_account_wa_id')
    )
    with op.batch_alter_table('whatsapp_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_contacts_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_contacts_wa_id'), ['wa_id'], unique=False)

    op.create_table('whatsapp_conversations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('contact_id', sa.String(length=32), nullable=False),
    sa.Column('openwebui_chat_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['whatsapp_contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openwebui_chat_id')
    )
    with op.batch_alter_table('whatsapp_conversations', schema=None) as batch_op:
        batch_op.create_index('ix_conversation_contact_status', ['contact_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_conversations_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_conversations_last_message_at'), ['last_message_at'], unique=False)

    op.create_table('whatsapp_messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('whatsapp_message_id', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sender_phone', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['whatsapp_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_message_id')
    )
    with op.batch_alter_table('whatsapp_messages', schema=None) as batch_op:
        batch_op.create_index('ix_message_conversation_created', ['conversation_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_messages_sender_phone'), ['sender_phone'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_messages_sender_phone'))
        batch_op.drop_index('ix_message_conversation_created')

    op.drop_table('whatsapp_messages')
    with op.batch_alter_table('whatsapp_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_conversations_last_message_at'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_conversations_account_id'))
        batch_op.drop_index('ix_conversation_contact_status')

    op.drop_table('whatsapp_conversations')
    with op.batch_alter_table('whatsapp_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_contacts_wa_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_contacts_account_id'))

    op.drop_table('whatsapp_contacts')
    op.drop_table('whatsapp_accounts')
    # ### end Alembic commands ###
